const BASE_URL = "https://dant3.net";

export type PublicJob = { id:string; ownerId:string; title:string; description:string; location:string|null; isRemote:boolean; employmentType:string; compensationText:string|null; status:string; createdAt:string; employerName:string; employerUrl:string|null; requirementsText:string|null; skills:string[]; applicantTypes:string[]; experienceLevel:string; };
export type PublicExternalJob = { id:string; sourceName:string; sourceUrl:string; sourceTermsUrl:string; sourceAttribution:string; companyName:string; title:string; summary:string; location:string|null; isRemote:boolean; employmentType:string; compensationText:string|null; applicantTypes:string[]; lastVerifiedAt:string; targetCountryCodes:string[]; publishedAt:string|null; };
export type ParsedJobLocation = { raw:string; city:string; state:string; country:string; remote:boolean; };
export function cleanText(value: unknown, maxLength = 20_000): string { return String(value ?? "").replace(/\u0000/g, "").replace(/\r\n?/g, "\n").trim().slice(0, maxLength); }
export function isNonProductionJob(job: Pick<PublicJob,"title"|"description">): boolean { const title=cleanText(job.title,180); const description=cleanText(job.description,500); const explicitTitleMarker=/^\s*(?:\[(?:test|demo|sample)\]|\((?:test|demo|sample)\)|(?:test|demo|sample)\s+only\b)/i; const explicitDescriptionMarker=/^\s*(?:this\s+is\s+)?(?:a\s+)?(?:test|demo|sample)\s+(?:job|listing|vacancy)\b/i; return explicitTitleMarker.test(title)||explicitDescriptionMarker.test(description); }
export function isSyndicationEligible(job: PublicJob): boolean { return Boolean(job.id&&job.status==="open"&&!isNonProductionJob(job)&&job.title.length>=5&&job.description.length>=50&&job.location&&!Number.isNaN(Date.parse(job.createdAt))); }
export function parseJobLocation(value:string|null):ParsedJobLocation { const raw=cleanText(value,180); const remote=/\b(remote|work from home|telecommute|distributed)\b/i.test(raw); const parts=raw.split(",").map(p=>p.trim()).filter(Boolean); if(parts.length>=3)return{raw,city:parts[0],state:parts.slice(1,-1).join(", "),country:parts.at(-1)??"",remote}; if(parts.length===2)return{raw,city:parts[0],state:"",country:parts[1],remote}; return{raw,city:remote?"":raw,state:"",country:"",remote}; }
export function mapEmploymentType(value:string):string { const normalized=value.toLowerCase().replace(/[\s_]+/g,"-"); if(normalized.includes("full"))return"FULL_TIME"; if(normalized.includes("part"))return"PART_TIME"; if(normalized.includes("intern"))return"INTERN"; if(normalized.includes("temporary"))return"TEMPORARY"; if(normalized.includes("volunteer"))return"VOLUNTEER"; if(normalized.includes("per-diem"))return"PER_DIEM"; if(normalized.includes("contract")||normalized.includes("freelance"))return"CONTRACTOR"; return"OTHER"; }
export function jobDetailUrl(jobId:string,source?:string):string { const url=new URL(`/job-board/${encodeURIComponent(jobId)}`,BASE_URL); const safeSource=cleanText(source,40).toLowerCase(); if(/^[a-z0-9_-]{2,40}$/.test(safeSource)){url.searchParams.set("utm_source",safeSource);url.searchParams.set("utm_medium","job_syndication");} return url.toString(); }
export function escapeHtml(value:unknown):string { return cleanText(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;"); }
export function jobDescriptionHtml(description:string):string { return cleanText(description).split(/\n{2,}/).map(p=>`<p>${escapeHtml(p).replace(/\n/g,"<br>")}</p>`).join(""); }
export function toJobPosting(job:PublicJob):Record<string,unknown>|null { if(!isSyndicationEligible(job))return null; const location=parseJobLocation(job.location); const structured:Record<string,unknown>={"@context":"https://schema.org","@type":"JobPosting",title:job.title,description:jobDescriptionHtml(job.description),identifier:{"@type":"PropertyValue",name:"Dant3",value:job.id},datePosted:new Date(job.createdAt).toISOString(),employmentType:mapEmploymentType(job.employmentType),hiringOrganization:{"@type":"Organization",name:job.employerName||"confidential",...(job.employerUrl?{sameAs:job.employerUrl}:{})},url:jobDetailUrl(job.id),directApply:false,...(job.skills.length?{skills:job.skills.join(", ")}:{})}; if(location.remote||job.isRemote){structured.jobLocationType="TELECOMMUTE";if(location.country)structured.applicantLocationRequirements={"@type":"Country",name:location.country};}else if(location.raw){structured.jobLocation={"@type":"Place",address:{"@type":"PostalAddress",addressLocality:location.city,...(location.state?{addressRegion:location.state}:{}),...(location.country?{addressCountry:location.country}:{})}};} return structured; }
export function escapeXml(value:unknown):string { return cleanText(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&apos;"); }
export function cdata(value:unknown):string { return `<![CDATA[${cleanText(value).replace(/]]>/g,"]]]]><![CDATA[>")}]]>`; }
