custom:
  - https://buy.stripe.com/6oU9AV2s33E639L3q4cfK06
  - https://buy.stripe.com/28E3cx1nZ2A26lXaSwcfK05
  - https://donate.stripe.com/8x214pd6Ha2ueSt0dScfK04
  - https://donate.stripe.com/fZucN7eaL7Um39Ld0EcfK03
